# Replace the <> value with the actual value
[masters]
control-plane-node ansible_host=<remote-host> ansible_user=<username> ansible_ssh_private_key_file=<ssh-key-path>

[workers]
worker-node-1 ansible_host=<remote-host> ansible_user=<username> ansible_ssh_private_key_file=<ssh-key-path>
worker-node-2 ansible_host=<remote-host> ansible_user=<username> ansible_ssh_private_key_file=<ssh-key-path>

[all:vars]
ansible_python_interpreter=/usr/bin/python3
